### ISSUE TITLE
No luasandbox/lua.h

### ISSUE THREAD

**Issue by ZhangYet** [mozilla-services/lua_sandbox#136]
After runnging `cmake -DCMAKE_BUILD_TYPE=release ..` and `Makefile` has been gernerated, I'm going to `make`, but came up with an error.
Here is the error message
```
[  1%] Building C object src/util/CMakeFiles/luasandboxutil.dir/heka_message.c.o
[  2%] Building C object src/util/CMakeFiles/luasandboxutil.dir/heka_message_matcher.c.o
In file included from /root/repo/lua_sandbox/src/util/heka_message_matcher.c:15:0:
/root/repo/lua_sandbox/release/ep_base/include/luasandbox.h:68:28: fatal error: luasandbox/lua.h: No such file or directory
#include "luasandbox/lua.h"
```

**Comment by ZhangYet** [comment]
And I'm using cmake 3.5.2.

**Comment by ZhangYet** [comment]
I am going to install lua_sandbox to install hindsight. And https://github.com/mozilla-services/heka/issues/1918 didn't solve my problem.

**Comment by ZhangYet** [comment]
In fact, I make soft link of `lua.h`, `lualib.h` and `lauxlib.h` from `/usr/include` to my build path. 
I installed `lua_sandbox` in my docker container(a simple CentOS 7 image), I don't know if this is related.

**Comment by trink** [comment]
I cannot reproduce this problem on centos7.  Please rm -rf your build directory and attempt to rebuild the current master branch from scratch.  If it still fails please provide the complete build output up to the point of failure.

**Comment by trink** [comment]
I was able to reproduce it the will be a fix posted shortly

**Comment by trink** [comment]
849ba0b52f01c97c6e1582ef51304f1b626a1f94
