### ISSUE TITLE
compilation failing

### ISSUE THREAD

**Issue by Madhu1512** [mozilla-services/lua_sandbox#144]
i am try to compile lua_sandbox from master branch on mac osx and it's throwing following error during make.

Scanning dependencies of target copy_includes
[  0%] Built target copy_includes
Scanning dependencies of target luasandboxutil
[  0%] Building C object src/util/CMakeFiles/luasandboxutil.dir/heka_message.c.o
[  1%] Building C object src/util/CMakeFiles/luasandboxutil.dir/heka_message_matcher.c.o
[  2%] Building C object src/util/CMakeFiles/luasandboxutil.dir/heka_message_matcher_parser.c.o
[  2%] Building C object src/util/CMakeFiles/luasandboxutil.dir/input_buffer.c.o
[  3%] Building C object src/util/CMakeFiles/luasandboxutil.dir/output_buffer.c.o
[  4%] Building C object src/util/CMakeFiles/luasandboxutil.dir/protobuf.c.o
[  5%] Building C object src/util/CMakeFiles/luasandboxutil.dir/running_stats.c.o
[  5%] Building C object src/util/CMakeFiles/luasandboxutil.dir/string.c.o
[  6%] Building C object src/util/CMakeFiles/luasandboxutil.dir/string_matcher.c.o
[  7%] Building C object src/util/CMakeFiles/luasandboxutil.dir/util.c.o
/Users/madhu/lua_sandbox/src/util/util.c:57:29: error: expected ')'
  FILE *fh = fopen(fn, "rb" CLOSE_ON_EXEC);
                            ^
/Users/madhu/lua_sandbox/src/util/util.c:57:19: note: to match this '('
  FILE *fh = fopen(fn, "rb" CLOSE_ON_EXEC);
                  ^
1 error generated.
make[2]: *** [src/util/CMakeFiles/luasandboxutil.dir/util.c.o] Error 1
make[1]: *** [src/util/CMakeFiles/luasandboxutil.dir/all] Error 2
make: *** [all] Error 2

**Comment by trink** [comment]
I am in the process of making the final 1.0 API changes. There will be a cleanup pass for OSX and Windows (most likely next week). The last SHA tested with OSX is 92b4725d18c0e76e004eebf4772bf7abedededb5

**Comment by trink** [comment]
closed in master
