### ISSUE TITLE
Please create tags for all lua-sandbox releases

### ISSUE THREAD

**Issue by rhertzog** [mozilla-services/lua_sandbox#156]
I noticed that at the github releases pages has version 1.0.3 as the latest version, yet when you look at the history of https://github.com/mozilla-services/lua_sandbox/commits/master/CMakeLists.txt you will see version 1.0.4, 1.0.5 an 1.1.0.

I would highly recommend to not bump the version together with other changes. Make it a single commit changing only this and make a new tag pointing to this commit so that it's really clear that the new version is released (otherwise we might assume that you are only preparing the next release and bumped the version but you intend to make other changes before release).

Thank you. I noticed this while starting to work on a Debian package for lua-sandbox.

**Comment by rhertzog** [comment]
BTW same applies for hindsight (there it's even worse as there are no tags at all). If you want me to open the same ticket on hindsight, let me know. Otherwise I assume once is enough as it's about your release procedure, not really about the product itself.

**Comment by trink** [comment]
The version is bumped in a working branch once it is merged to master it is considered released.  I will go back and tag the merges, thanks.

**Comment by trink** [comment]
As for Hindsight there will be no tagging while it is under heavy development.  The master branch is the source of truth and there will be no support of previous versions.  The versioning is strictly there for package dependency management.

**Comment by trink** [comment]
The tags have been added
