### ISSUE TITLE
Build fails when git is not available but git is no longer required

### ISSUE THREAD

**Issue by rhertzog** [mozilla-services/lua_sandbox#158]
Now that the lua extensions have been moved to a separate project, lua-sandbox no longer needs to have git available for its build. Yet it will still look for it:
```
CMake Error at /usr/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Git (missing: GIT_EXECUTABLE)
```

Please drop that requirement.

**Comment by sathieu** [comment]
See PR #159.
