### ISSUE TITLE
Accessing ENV variable from cfg file

### ISSUE THREAD

**Issue by deric** [mozilla-services/lua_sandbox#169]
Is it possible to access ENV variables from configuration files?

Or the best way is to put this kind of code into `lua` files?
```
require "os"
local myvar   = os.getenv("MYVAR")
```
Can I set also variables like `message_matcher` from lua code?

**Comment by trink** [comment]
Please use the mailing list for support questions; the issue tracker is meant for tracking bug reports and feature requests, thank you.
https://mail.mozilla.org/listinfo/hindsight
