### ISSUE TITLE
Build failed on CentOS 6.6

### ISSUE THREAD

**Issue by liuyangc3** [mozilla-services/lua_sandbox#174]
hi
I am following these steps
```
git clone https://github.com/mozilla-services/lua_sandbox.git
cd lua_sandbox
mkdir release
cd release
cmake -DCMAKE_BUILD_TYPE=release ..
make
```
and got error

![image](https://cloud.githubusercontent.com/assets/6705844/21177749/71bc8372-c227-11e6-99e2-ffc0eba61a76.png)

env:
* OS: CentOS 6.6
* gcc: 4.8.2
* cmake: 3.7

**Comment by trink** [comment]
The fix is to update your binutils so that you get a newer version of an assembler which accepts this instruction. You can query the current version by typing "as --version".  I am running 2.23.52.0.1
