### ISSUE TITLE
cpack -G DEB fails while running dpkg-shlibdeps

### ISSUE THREAD

**Issue by hblanks** [mozilla-services/lua_sandbox#175]
When building a sandbox debian package from current master or v1.2.1, as instructed by the README, from an Ubuntu 16.10 machine, I get:

```
CPack: Create package using DEB
CPack: Install projects
CPack: - Run preinstall target for: luasandbox
CPack: - Install project: luasandbox
CPack: Create package
CPackDeb: - Generating dependency list
CMake Error at /usr/share/cmake-3.5/Modules/CPackDeb.cmake:530 (message):
  CPackDeb: dpkg-shlibdeps: 'dpkg-shlibdeps: error: couldn't find library
  libluasandboxutil.so.0 needed by ./usr/bin/lsb_heka_cat (ELF format:
  'elf64-x86-64'; RPATH: '')

  dpkg-shlibdeps: warning: binaries to analyze should already be installed in
  their package's directory

  dpkg-shlibdeps: warning: binaries to analyze should already be installed in
  their package's directory

  dpkg-shlibdeps: error: couldn't find library libluasandbox.so.0 needed by
  ./usr/lib/libluasandboxtest.so.1.2.1 (ELF format: 'elf64-x86-64'; RPATH:
  '')

  dpkg-shlibdeps: warning: binaries to analyze should already be installed in
  their package's directory

...
```

Output of the failure ends with:

```
  binary files:
  './usr/bin/lsb_heka_cat;./usr/lib/libluasandbox.so.1.2.1;./usr/lib/libluasandboxheka.so.1.2.1;./usr/lib/libluasandboxtest.so.1.2.1;./usr/lib/libluasandboxutil.so.1.2.1'
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/CPackDeb.cmake:778 (cpack_deb_prepare_package_vars)
  

CPack Error: Error while execution CPackDeb.cmake
CPack Error: Problem compressing the directory
CPack Error: Error when generating package: luasandbox
```

I am able to build a TGZ package with no issue.

Is there something I'm missing?

**Comment by trink** [comment]
Try setting CPACK_DEBIAN_PACKAGE_SHLIBDEPS to OFF

**Comment by trink** [comment]
Removed the setting 43b789e927ec949265f4d1797c2bdfb403804ecb

**Comment by hblanks** [comment]
The way of the cmake is new to me. Thanks for the fix!

**Comment by mattmilten** [comment]
We just ran into a similar issue. Do you mind shedding some light on this? Especially; Did you experience any regressions after removing this "feature"?

**Comment by trink** [comment]
@mattmilten What distro/version of Debian and what version of CMake

**Comment by mattmilten** [comment]
That's Ubuntu 16.04. and CMake 3.5.1.  This error message suddenly came up and the only reference I found was in here. I fear that removing the shlib dependencies, the debian package no longer knows what it depends on, so the user need to install the missing packages later on.

**Comment by mattmilten** [comment]
Oh, please excuse the confusion! I wasn't building lua-sandbox but rather my own project. I simply facedthe exact same error with the same solution - I just wantedto know whether you did experience any regressions or downgradesafter removing this line from your CMake configuration.

**Comment by trink** [comment]
No problem; our, production systems are Centos7 but we have a couple of test instances setup with Debian and haven't had any issues with the packages after the change.
