### ISSUE TITLE
Fix sporadic unit test failure (test runs fast enough to produce a 0 measurement)

### ISSUE THREAD

**Issue by trink** [mozilla-services/lua_sandbox#185]
line: 464 (0 < stats.pm_avg) received 0

**Comment by sathieu** [comment]
I think this is because it's too fast. Adding some sleep will help.

**Comment by trink** [comment]
Increasing the test run time still didn't correct the problem; this will require further investigation

**Comment by sathieu** [comment]
For reference, see https://bugs.debian.org/856177 (with a not-proposed patch ;-)

**Comment by trink** [comment]
Closed by https://github.com/mozilla-services/lua_sandbox/pull/200/commits/94d54341c6ac4e608baf8702e8f37b16b5ce5ce9
