### ISSUE TITLE
Cannot rebuild for Heka

### ISSUE THREAD

**Issue by balintzs** [mozilla-services/lua_sandbox#216]
Hi!

We have a few legacy systems that use Heka sidecar containers from an old fork of Heka. We didn't need to rebuild the container for months, but now that we do we face the problem of a missing dependency: **https://github.com/trink/lua.git**
See https://github.com/mozilla-services/lua_sandbox/blob/heka/cmake/externals.cmake#L67
Could you update the dependency, or reinstate the `trink/lua` repository?

Many thanks!

cc @trink

**Comment by trink** [comment]
#209
