### ISSUE TITLE
Hindsight

### ISSUE THREAD

**Issue by Jitoxxx** [mozilla-services/lua_sandbox#220]
Hello, 

I'm a student, doing an internship about Centralized Logging.
I've made a few basic setups, but I'm trying to expand my experience with all kinds of systems.
(Elastic Stack, Graylog,... )

I came on Hindsight/Heka through research.

I recently tried to buildup hindsight, unfortunately I'm inexperienced with LUASandbox, CMake, and Hindsight.

made a new directory: /home/ubuntu/tmp/hindsight/release/...
                                     /home/ubuntu/tmp/lua_sandbox/release/...

I followed the Luasandbox and hindsight on CMake build instructions:

But I keep getting stuck here:
![error](https://user-images.githubusercontent.com/18415449/38092640-1a25a94a-3369-11e8-934a-4d23654f593f.png)

Also added PREFIX_PATH of LUASANDBOX in my CMakeLists.txt

Sorry to take up your time and I already saw someone with this issue but didn't really get the right way to work around this.

greets,
Joachim

**Comment by ameihm0912** [comment]
@Jitoxxx you might want to have a look over at https://github.com/mozilla-services/lua_sandbox_extensions/tree/dev, specifically https://github.com/mozilla-services/lua_sandbox_extensions/blob/dev/Dockerfile

lua_sandbox_extensions are all the plugins for hindsight/lua_sandbox, and in this repo we build a docker image that contains all of the above. The Dockerfile could be a good reference if you'd like to build it manually.

**Comment by Jitoxxx** [comment]
@ameihm0912 

Thank you for the reply, Can't seem to get it to work on my Ubuntu for some reason.
So I'm using docker to test out hindsight, It's probably not going into production anyway.

Kind regards and thanks again,
Jitoxxx

**Comment by ameihm0912** [comment]
No problem; yeah the docker image will work for what you need

FWIW as well, you could also try building on Centos 7 vs. Ubuntu if it was issues in the extensions you are running into. There are a few extensions that do not work properly with some of the distribution packaged dependencies like OpenSSL there.
