### ISSUE TITLE
Apache Log Format Bug

### ISSUE THREAD

**Issue by andrewhampton** [mozilla-services/lua_sandbox#69]
%T should be parsed as a double, but is parsed as an int. This causes request times such as "0.23" to be parsed as "0" in the heka message.

I think "integer" in common_log_format.lua:163 should be changed to "double".

https://github.com/mozilla-services/lua_sandbox/blob/dev/modules/common_log_format.lua#L163

**Comment by andrewhampton** [comment]
After talking a bit more in IRC to RaFromBRC, it seems it should probably actually be changed to `double + integer` since hitting an even number is shown as "1", not "1.000".

**Comment by trink** [comment]
I took a look at the Apache 2.4.12 code mod_log_config.c line 771
```c
    return apr_psprintf(r->pool, "%" APR_TIME_T_FMT, apr_time_sec(duration));
```
Depending on what version of the APR is being used APR_TIME_T_FMT is either 'lld' or 'ld' so definitely not a decimal output.  What web server/version are you using?

**Comment by andrewhampton** [comment]
I'm using hipache. https://github.com/hipache/hipache

**Comment by trink** [comment]
Hmm. not sure we want to change the Apache parser to comply with a non Apache log.

**Comment by andrewhampton** [comment]
That makes sense. Any suggestions on the best way for me to handle this?

**Comment by rafrombrc** [comment]
@trink Does the proposed change increases Heka's usefulness. Are there any drawbacks? Does introducing the 'or' clause hurt parsing performance?

**Comment by trink** [comment]
When parsing a real Apache log the two branches would always have to be evaluated (so technically yes it is less efficient).  However, my real concern is this won't be the only difference in output (from whatever 'Apache like' source) and as time goes by we end up with a shitty grammar.

As for how do we support variants without having the user patch or replicate the grammar; I have only one thought and I am not loving it.  We could expose the apache_format_variables table then people could override various specifiers from their sandbox without having to reimplement the world.

**Comment by trink** [comment]
Closing, if we open up access to the apache grammar internal variables the argument could be made to open up access for all grammars.  If more use cases arrive in the future to use/modify grammar fragments this can be re-evaluated.
