### ISSUE TITLE
syslog decoder unable to parse structured data

### ISSUE THREAD

**Issue by jedisct1** [mozilla-services/lua_sandbox#93]
RFC5424 includes support structured data, that `modules/syslog.lua` is trying to parse

Structured data looks like:

    [abcd@42 software="test" swVersion="0.0.1"]

The parser for this is:

```lua
local hostname        = nilvalue + printusascii^-255
local sd_name         = printusascii^-32
local param_name      = sd_name
local param_value     = utf8_string
local sd_param        = param_name * '="' * param_value * '"'
local sd_id           = sd_name
local sd_element      = l.P"[" * sd_id * (sp * sd_param)^0 * "]"
```

Unfortunately, this grammar is incorrect, and the parser is actually unable to parse `sd_element`.

`printusascii` includes the `=` character, `sd_name` is greedier than expected. [RFC 5424](http://tools.ietf.org/html/rfc5424#section-6.2.3) explicitly prevents this in its definition, by disallowing a few characters:

    SD-NAME         = 1*32PRINTUSASCII ; except '=', SP, ']', %d34 (")

Changing the Lua equivalent to:
```lua
local sd_name         = (printusascii - l.S'=]"' - sp)^-32
```
Makes the parser properly handle property names.

Unfortunately, `param_value` has the same issue, `utf8_string` includes the `"` character.

A terrible workaround is:
```lua
local param_value     = (octet - l.P'"')^0
```

But of course, this would miserably fail with values containing escaped characters.

**Comment by trink** [comment]
Yeah param_value would have to allow the escaped versions of `"`, `'`, `]` but it can be fixed up as well.

**Comment by jedisct1** [comment]
Indeed, something like

```lua
local esc             = l.P"\\"
local param_value_esc = l.S"\"']\\"
local param_value     = ((octet - param_value_esc) + (esc * param_value_esc))^0```

might be enough to fix it.

**Comment by trink** [comment]
It would still have to work for something like "foo\bar".  The sd_name grammar can be simplified too.  Are you interested in submitting a PR for this?

**Comment by jedisct1** [comment]
`foo\bar` would have to be written `foo\\bar`. I don't think that `foo\bar` is correct according to the RFC.

I can certainly submit a PR for this.

**Comment by jedisct1** [comment]
Stupid question: aren't we supposed to capture (`name`, `value`) pairs here?

**Comment by trink** [comment]
That is definitely an option, otherwise it will just capture the entire string.  Breaking it into individual message fields would be very useful we just didn't have the need (you are the first to use the structured format)

**Comment by jedisct1** [comment]
Having the parser return a table with the fields is probably better than returning the entire string that will have to be parsed anyway.

I'm gonna add this to my initial pull request.

**Comment by jedisct1** [comment]
Done, PR updated.

Looking at the `\` issue.

**Comment by jedisct1** [comment]
Can you look at the PR again?

`foo\bar` is now allowed, and the captured fields are returned as a table.

**Comment by jedisct1** [comment]
Can you review the current PR?
