### ISSUE TITLE
Consider adding lua-MessagePack module

### ISSUE THREAD

**Issue by salekseev** [mozilla-services/lua_sandbox#97]
I was wondering if it would be possible to add https://github.com/fperrad/lua-MessagePack/ as an available module. This would give a path to develop Heka encoders/decoders that communicate with http://www.fluentd.org/ natively and are maybe able to replace it.

**Comment by trink** [comment]
You can use external modules so this is possible today.  However, since it is not core functionality to most users I would prefer to not pre-package it with the sandbox.
